import ollama


def generate_blog(topic, style, tone, word_count):

    prompt = f"""
    Write a high-quality blog about the following topic:

    Topic: {topic}

    Writing Style: {style}

    Tone: {tone}

    Word Count: approximately {word_count} words.

    Requirements:
    - Give the blog a clear introduction.
    - Use meaningful headings.
    - Explain the topic clearly.
    - Include relevant examples.
    - End with a conclusion.
    - Do not mention that the content was generated by AI.
    """

    response = ollama.chat(
        model="llama3.2",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response["message"]["content"]